Deployment improvements
This changes the workflow order so that the Sentry deployment comes first. It also gives better logging for the wait for the services to stabilise rather than just showing nothing for three or so minutes. There is room for optimisation but I will come back to it.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,12 +6,75 @@ on:
   workflow_dispatch:
 
 jobs:
+  deploy-sentry:
+    runs-on: ubuntu-latest
+    if: ${{ github.repository == 'alextheman231/lexicon' }}
+    permissions:
+      contents: read
+    env:
+      SENTRY_RELEASE: ${{ github.sha }}
+    steps:
+      - name: Checkout the repository
+        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
+        with:
+          persist-credentials: false
+
+      - name: Install PNPM
+        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
+        with:
+          run_install: false
+
+      - name: Install Node.js
+        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
+        with:
+          node-version: 22
+          cache: "pnpm"
+
+      - name: Cache Turborepo cache
+        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
+        with:
+          path: "**/.turbo"
+          key: turbo-deploy-${{ hashFiles('{apps,packages}/**', 'package.json', 'pnpm-lock.yaml', 'pnpm-workspace.yaml', 'turbo.json') }}
+          restore-keys: turbo-deploy-
+
+      - name: Install dependencies
+        run: pnpm install
+
+      - name: Build packages
+        run: pnpm run build
+
+      - name: Create Sentry release for back-end
+        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0
+        env:
+          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_ORGANISATION_TOKEN }}
+          SENTRY_ORG: alextheman231
+          SENTRY_PROJECT: lexicon-back-end
+        with:
+          environment: production
+          release: ${{ env.SENTRY_RELEASE }}
+          ignore_missing: true
+          ignore_empty: true
+
+      - name: Create Sentry release for front-end
+        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0
+        env:
+          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_ORGANISATION_TOKEN }}
+          SENTRY_ORG: alextheman231
+          SENTRY_PROJECT: lexicon-front-end
+        with:
+          environment: production
+          release: ${{ env.SENTRY_RELEASE }}
+          sourcemaps: apps/front-end/dist/assets
+          ignore_missing: true
+          ignore_empty: true
+
   deploy-app:
     runs-on: ubuntu-latest
     if: ${{ github.repository == 'alextheman231/lexicon' }}
     permissions:
       contents: read
       id-token: write
+    needs: [deploy-sentry]
     steps:
       - name: Checkout the repository
         uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
@@ -109,69 +172,35 @@ jobs:
 
       - name: Wait for service to stabilise
         env:
+          AWS_REGION: ${{ vars.AWS_REGION }}
           AWS_CLUSTER_NAME: ${{ vars.AWS_CLUSTER_NAME }}
           AWS_SERVICE_NAME: ${{ vars.AWS_SERVICE_NAME }}
-        run: aws ecs wait services-stable --cluster "$AWS_CLUSTER_NAME" --service "$AWS_SERVICE_NAME"
+        run: |
+          while true; do
+            ROLLOUT_STATE=$(
+              aws ecs describe-services \
+                --cluster "$AWS_CLUSTER_NAME" \
+                --services "$AWS_SERVICE_NAME" \
+                --query "services[0].deployments[?status=='PRIMARY'].rolloutState | [0]" \
+                --output text
+            )
+            echo "Primary deployment state: $ROLLOUT_STATE"
 
-  deploy-sentry:
-    runs-on: ubuntu-latest
-    if: ${{ github.repository == 'alextheman231/lexicon' }}
-    permissions:
-      contents: read
-    env:
-      SENTRY_RELEASE: ${{ github.sha }}
-    needs: [deploy-app]
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
-        with:
-          persist-credentials: false
+            aws ecs describe-services \
+              --cluster "$AWS_CLUSTER_NAME" \
+              --services "$AWS_SERVICE_NAME" \
+              --query 'services[0].events[0:5].[createdAt,message]' \
+              --output table
 
-      - name: Install PNPM
-        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
-        with:
-          run_install: false
+            if [ "$ROLLOUT_STATE" = "FAILED" ]; then
+              echo "Deployment failed."
+              exit 1
+            fi
 
-      - name: Install Node.js
-        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
-        with:
-          node-version: 22
-          cache: "pnpm"
+            if [ "$ROLLOUT_STATE" = "COMPLETED" ]; then
+              echo "Service is stable."
+              break
+            fi
 
-      - name: Cache Turborepo cache
-        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
-        with:
-          path: "**/.turbo"
-          key: turbo-deploy-${{ hashFiles('{apps,packages}/**', 'package.json', 'pnpm-lock.yaml', 'pnpm-workspace.yaml', 'turbo.json') }}
-          restore-keys: turbo-deploy-
-
-      - name: Install dependencies
-        run: pnpm install
-
-      - name: Build packages
-        run: pnpm run build
-
-      - name: Create Sentry release for back-end
-        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0
-        env:
-          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_ORGANISATION_TOKEN }}
-          SENTRY_ORG: alextheman231
-          SENTRY_PROJECT: lexicon-back-end
-        with:
-          environment: production
-          release: ${{ env.SENTRY_RELEASE }}
-          ignore_missing: true
-          ignore_empty: true
-
-      - name: Create Sentry release for front-end
-        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0
-        env:
-          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_ORGANISATION_TOKEN }}
-          SENTRY_ORG: alextheman231
-          SENTRY_PROJECT: lexicon-front-end
-        with:
-          environment: production
-          release: ${{ env.SENTRY_RELEASE }}
-          sourcemaps: apps/front-end/dist/assets
-          ignore_missing: true
-          ignore_empty: true
+            sleep 15
+          done
